name: joker
description: "A Joke Telling Robot Mobile App built with Flutter."

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.8.5
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   # # Add your app icons and other assets here
  #   # - assets/

version: 1.0.0+1
